### PR TITLE
Sanitize & parse posts text

### PR DESCRIPTION
**Pull request by toddhow**
Currently the text field data isn't sanitized & parsed to remove any HTML leftover from scraping. I added a small bit of code to cleanup the text before adding it to the DB.

Also adds fixes for post_id and missing dependencies

### CODE REVIEW

**Comment by toddhow** [comment]
Added fix for post_id unrelated to PR goal

**Comment by toddhow** [comment]
Made `sanitize_text` function and put it in its own util file

**Comment by toddhow** [comment]
Added `text_` to access non sanitized `text`

**Comment by datawhores** [comment]
I merge this manually

**Comment by datawhores** [comment]
Your account isn't really attributed
There's a way to maybe fix it, but I would need your noreply email

**Pull request closed without merging**
