### PR TITLE
Scrape labels

### PR DESCRIPTION
**Pull request by merqwury**
Support for scrapping labels

### CODE REVIEW

**Comment by datawhores** [comment]
gonna put somethings I should do before merging

sync with aiohttp changes

classes should probably be in their own folder, with labels.py being a file with the Labels class

might have to change labels to an extension of post class, so it can access of that classes methods.

If labels are the only option selected we can save work by only scraping labels. However if all options are selected then we probably should not scrape labels







Having labels as a post type has an advantage of being usable by those who don't use command args. Though I don't think they are seperate from the main timeline other then 
"archived"

so if "Labels" in args.posts or "All" in args.posts should probably change to


Maybe there should be an arg to fitler by label type

The docs should be updated with changes to args and doc

**Comment by datawhores** [comment]
https://github.com/datawhores/OF-Scraper/pull/105

**Comment by merqwury** [comment]
I can make the changes above but I'm currently travelling so might take me a few days.

- Agree on a separate folder for classes, I was just following the Post class being in posts.py
- As for making Label and extension of Post, I don't see the relevance between the two to by a subclass. However.. I could make Label class instead of storing post_ids, to store an Object of Post instead.
- If "All" is selected, why would you not want to scrape Labels?
- For filtering, we can probably allow filtering by Label text and/or id

**Comment by datawhores** [comment]
Aren't labels a subsect of All 

Like if your getting all your also getting all the labeled post as well. 

My understanding is that if your on the regular timeline then you would see all the labeled posts.

**Comment by merqwury** [comment]
> Aren't labels a subsect of All
> 
> Like if your getting All your also getting all the labeled post as well.
> 
> My understanding is that if your on the regular timeline then you would see all the labeled posts.
> 
> Yeah the subclass thing is because that how all the other scrapers work. It might not be needed but best to use the debugger to confirm.
> 
> I wanted to see how it works with download.py and like.py

That's partly correct, however, when retriving posts/timeline, the labels aren't returned with the posts, hence why you need to do it separately. I still believe, we should allow "Labels" as an option to only scrape those, and when "All" is selected, then it will scrape them as well.

Also, looking at the filtering codepath, it seems that all filters apply on the Media class. However, media derived from Labels->Posts, would not have any information about the labels on them.

Generally speaking, media aren't particularly relevant when looking at labels. What really interests us are the posts per label. Unless we want to enhance filtering, to take in a particular label, and download ONLY that label's media/posts.

I'll push what I have until now for further discussion

**Pull request closed without merging**
